### ISSUE TITLE
Array Path Help

### ISSUE THREAD

**Issue by ReynerHL** [bhoriuchi/vue-deepset#1] opened 2017-08-14 22:51 UTC
In resume....Using Vuex, I would like to reference Object properties inside an Array. For example, I have the following store state.
```js
order:{
  orderProducts:[
    {
      unit_cost:10.5
    },
    {
      unit_cost: 13.4
    }
  ],
  testing:1
}
```
Using this in an input works well....so the mutation is triggering well.
`v-model="order['testing']"`

Now, the following retrieve well the value but...launch an error:
`v-model="order['orderProducts[0[unit_cost]]']"`

Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

Can some one explain how to target Objects properties inside an Array when declaring the path?
Thanks in advance.

**Comment by bhoriuchi** [comment] 2017-08-15 00:03
this 
```
v-model="order['orderProducts[0[unit_cost]]']"
```

should look like this

```
v-model="order['orderProducts[0].unit_cost']"
```
let me know if it was a typo on your part.

Also, arrays in vue require you to use the built in array methods (push, pop, slice, etc...) which are not implemented in `vue-deepset` currently

your data object looks fine.

**Comment by bhoriuchi** [comment] 2017-08-15 00:25
Actually there is a bug in the code for arrays. ill work on a fix and hopefully have something out shortly. thanks for the find!

**Comment by ReynerHL** [comment] 2017-08-15 00:27
No, thanks you for your quick reply. This work is very helpful from my point of view. Hope you can get it fixed.

**Comment by bhoriuchi** [comment] 2017-08-15 00:50
please try `v0.3.1` and see if that fixes your issue. also currently all values will be converted to strings when modified and array indexes that dont exist in the data object/store are not handled. i will look to handle these issues in the future

**Comment by ReynerHL** [comment] 2017-08-15 00:53
I will check it right away !!

**Comment by ReynerHL** [comment] 2017-08-15 01:03
Sorry @bhoriuchi, the patch did not work for me.  :(
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."
Will you have any example mounted on https://jsfiddle.net/ so we can check it out better?
I'm using the same store.state but now I'm using your recomendation for the v-model attributes path:
v-model.number="order['orderProducts[0][unit_cost]']"

Again the value is well retrieved but the error comes when we try to change it.

**Comment by bhoriuchi** [comment] 2017-08-15 01:28
There are examples in the test folder of the project. I will look to get a fiddle set up

**Comment by bhoriuchi** [comment] 2017-08-15 01:30
alao please post your full related code so I can reproduce

**Comment by ReynerHL** [comment] 2017-08-15 01:45
@Thanks for your concern. I checked the examples in the test folder, but I did not found any using this kind of structure (arrays as object container). My code is more complex than I've published before, that's why I only showed the root of my problem. If we can reach the property of an object stored in an array, then my project will run.

Here you have the basic part of my store:
```js
state: {
                        order: {
                            orderProducts: [
                                {                                    
                                    unit_cost: 10.23,
                                    quantity: 10,
                                    discount: {
                                        promotions: [12, 1],
                                    },
                                    visibleDetail: false,
                                    isEditing: true
                                },
                                {                                    
                                    unit_cost: 11.23,
                                    quantity: 5,
                                    discount: {
                                        promotions: [12, 1],
                                    },
                                    visibleDetail: false,
                                    isEditing: false
                                }
                            ],
                            testing: 1
                        }
                    },
                    mutations: VueDeepSet.extendMutation({
                        ADD_NEW_ORDER_PRODUCT() {
                        },
                        SET_VISIBILITY_IN(state, payload) {
                            state.orderProducts[payload.index].visibleDetail = payload.visible;
                        },
                        SET_EDITED_STATE(state, payload) {
                            state.orderProducts[payload.index].isEditing = payload.visible;
                        }
                    }),
```

The component that uses this store has this computed property:
```js
computed: {
            order() {
                // The previous store is an store module, that's why the large string.
                return this.$deepModel('PurchaseModule.newOrder.order');
            },
            ...mapGetters('PurchaseModule/newOrder', {
                orderProductSubtotal: 'orderProductSubtotal',
                orderProductIVA: 'orderProductIVA',
                orderProductTotal: 'orderProductTotal',
                productCost: 'productCost'
            })
        }
```

And this component has this in ist template:

This works fine:
```html
<input type="number" v-model.number="order['testing']"/>
```

This only retrieve the value, but when we try to change it, it fails.

```html
<input type="number" v-model.number="order['orderProducts[0][unit_cost]']"/>
```

If you finally can set a fiddle example, I can put there my code.
Thanks again for your time.

**Comment by bhoriuchi** [comment] 2017-08-15 03:36
Here is a working fiddle https://jsfiddle.net/vbranden/gLzfe65f/

**Comment by ReynerHL** [comment] 2017-08-15 05:48
Thanks so much for provide an example.

Here is mine:
https://jsfiddle.net/reynerhl/m54h0gkh/

I've noticed that I'm using different versions for Vue and Vuex. The data is updated but if you open the chrome or mozilla dev tool, you will see the error.

My Chrome version is 60.0.3112.90 (Official Build) (64-bit)

**Comment by bhoriuchi** [comment] 2017-08-15 15:38
So i tracked the issue down to the vue version. It looks like there was a change introduced in `2.4.0` that is causing the data object to not use the proxy on first input change. I will continue to track down the issue, but a current workaround would be to use `vue@2.3.4`

I am also working on some fixes for the non-proxy code which would only impact users on browsers that dont support `Proxy` objects

**Comment by ReynerHL** [comment] 2017-08-15 16:27
@bhoriuchi But with the Vue version that you recomend it still showing the Error. Please, take a look:
https://jsfiddle.net/reynerhl/m54h0gkh/3/

I'm a little confused, if this is reported in the dev tool as an error, why the data in the store is actually updated? It seems like if this continue working, and the error is like a warning.

I can update the store with this approach:
https://vuex.vuejs.org/en/forms.html

But it requires some more typing comparing with your package. I would wait a little. Hope you can find the source of the error, and even better, provide a fix.

**Comment by bhoriuchi** [comment] 2017-08-15 16:50
it seems like using the proxy is the issue, when i use the composed object which is the proxy fallback everything seems to work on the newer version of vue. this does of course require everything to be predefined in the object. I will be adding a `{ useProxy: false }` option to the model functions so that you can specify not to use it and continue trying to figure out why the proxy isnt working.

See fiddle for upcomming changes. i have the entire deepset code in there

https://jsfiddle.net/vbranden/w35cfzgu/13/

**Comment by ReynerHL** [comment] 2017-08-15 19:11
Will you provide a patch update for this new option ({ useProxy: false }) or you preffer to wait until it can be solved?
Thanks in advance for your concern.

**Comment by bhoriuchi** [comment] 2017-08-15 19:21
i think i have actually solved the issue all together. Please try `vue-deepset@0.4.0` just published to npm.

to summarize the fix, i am still using proxys but they build an update a composed object. this seems to work better with the newer version of vue and it still allows for dynamic fields/paths to be added.

composed objects look at the source object and enumerate its fields into path strings, i.e.

```js
let myObj = {
  a: 1,
  b: [ { c: 1 }, { c: 2 } ]
}
```
would compose an object that looks like

```js
{
  'a': 1,
  'b': [ { c: 1 }, { c: 2 } ],
  'b[0]': { c: 1 },
  'b[0].c': 1,
  'b[1]': { c: 2 },
  'b[1].c': 2
}
```
that way when you `v-model="model['b[0].c']"` it just looks the key `b[0].c` up in the composed object

**Comment by ReynerHL** [comment] 2017-08-15 19:23
I will test it right away !

**Comment by ReynerHL** [comment] 2017-08-15 19:29
Can you please, update your fiddle ? So I can see how it would look like.

**Comment by bhoriuchi** [comment] 2017-08-15 19:32
updated fiddle https://jsfiddle.net/vbranden/gLzfe65f/ with the newer `vue` and `vuex` dists. the `vue-deepset` one is using rawgit so it updates automatically (after a few minutes) when i push changes to the repo

**Comment by ReynerHL** [comment] 2017-08-15 19:39
The fiddle fails if we use "strict: true" option in the store.

**Comment by bhoriuchi** [comment] 2017-08-15 19:47
hmm, i just updated it with strict:true and it is not giving me any errors
![screen shot 2017-08-15 at 12 46 30 pm](https://user-images.githubusercontent.com/10199502/29333233-dd6616a6-81b7-11e7-842f-c59184ee97d7.png)

maybe the cdn hasn't finished replicating? can you go to https://rawgit.com/bhoriuchi/vue-deepset/master/vue-deepset.js

and see if that file has a function `buildVuexModel` this is a new function for 0.4.0

**Comment by ReynerHL** [comment] 2017-08-15 19:59
My fiddle is working well now,
The fix is working well in my project, and now we can use this syntax to bind a particular array entry inside a v-for expresed in the template


```html
<template v-for="(orderProduct, key) in order.orderProducts">
........
<input type="number" class="form-control" min="1"
   v-model.number="order[`orderProducts[${key}].unit_cost`]" />
.......
```
There is only one thing that I would like to notice. Inspecting throught VueDevTool, it seems like the mutation VUEX_DEEP_SET is called twice for every model update.

Other than that... Well done @bhoriuchi. Your work saves lot of keystrokes.

**Comment by bhoriuchi** [comment] 2017-08-15 21:14
yeah i noticed that, would you mind opening up another issue for that and ill take a look at later. going to close this issue, fixed with https://github.com/bhoriuchi/vue-deepset/releases/tag/v0.4.0

**Closed as completed by bhoriuchi** 2017-08-15 21:14 UTC
